server:
  port: 8889
  
 #mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.153.129
    # Redis服务器连接端口
    port: 6379
    timeout: 60000
      